#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 27 10:59:45 2018

@author: andres
"""

import numpy as np
import matplotlib.pyplot as plt

signal = np.genfromtxt('TRIBICsignal.csv',delimiter=",")
print(signal)

plt.figure
plt.plot(signal)
plt.show()

